[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://shinobi-ux.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 